<?php

DEFINE('USERNAME',YOUR_MONGOLAB_USRENAME);
DEFINE('PASSWORD',YOUR_MONGOLAB_PASSWORD);
DEFINE('DBNAME',YOUR_MONGOLAB_DBNAME);
DEFINE('COLLECTION_NAME',YOUR_MONGOLAB_COLLECTIONNAME);

$conn_url = "mongodb://".USERNAME.":".PASSWORD."@ds029837.mongolab.com:29837/gj";
